### ISSUE TITLE
RandStream has no setDefaultStream

### ISSUE THREAD

**Issue by sqoingg** [Elucidation/UAV-Motion-Planner-Ensemble#2]
matlab outputs that 
class RandStream has no setDefaultStream
RandStream.setDefaultStream(RandStream('mt19937ar', 'Seed', SEED));
Could you help me?

**Comment by danghc-bit** [comment]
me too,did you have any answer,

**Comment by Elucidation** [comment]
Apologies all, it has been several years since any of us have touched this code. 

From what I can see [here](https://itectec.com/matlab/matlab-error-the-class-randstream-has-no-constant-property-or-static-method-named-setdefaultstream/) you should be replacing setDefaultStream with setGlobalStream , if this works for you let me know and I'll close the comment.

**Comment by danghc-bit** [comment]
> 抱歉，距离我们所有人接触此代码已有好几年了。
> 
> 从[这里](https://itectec.com/matlab/matlab-error-the-class-randstream-has-no-constant-property-or-static-method-named-setdefaultstream/)可以看到[，](https://itectec.com/matlab/matlab-error-the-class-randstream-has-no-constant-property-or-static-method-named-setdefaultstream/)您应该将setDefaultStream替换为setGlobalStream，如果对您有用，请告诉我，我将关闭注释。

wow,that's great, it worked,thanks,
